### ISSUE TITLE
Error Step 9: Duplicate column name 'image_attribute_id' 

### ISSUE THREAD

**Issue by DavidFeller** [akeneo/transporteo#92]
Error while migrating data from CE 1.7.9 to CE 2.0.0 in Step 9 (Families)

```
 [Akeneo\PimMigration\Domain\MigrationStep\s080_FamilyMigration\FamilyMigrationException]                                                                                          
  Error: Step 9 - Family Migration: Query "ALTER TABLE pim_catalog_family ADD COLUMN image_attribute_id INT(11) DEFAULT NULL AFTER label_attribute_id, ADD CONSTRAINT `FK_90632072BC295696` FOREIGN KEY (`image_attribute_id`) REFERENCES `pim_catalog_attribute` (`id`) ON DELETE SET NULL, ADD KEY `IDX_90632072BC295696` (`image_attribute_id`)" occured an error : SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'image_attribute_id'
```
```
  [Akeneo\PimMigration\Domain\DataMigration\QueryException]                                                                                                                         
  Query "ALTER TABLE pim_catalog_family ADD COLUMN image_attribute_id INT(11) DEFAULT NULL AFTER label_attribute_id, ADD CONSTRAINT `FK_90632072BC295696` FOREIGN KEY (`image_attr  
  ibute_id`) REFERENCES `pim_catalog_attribute` (`id`) ON DELETE SET NULL, ADD KEY `IDX_90632072BC295696` (`image_attribute_id`)" occured an error : SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'image_attribute_id'  
```

**Comment by DavidFeller** [comment]
Hi @LaurentPetard, 
I don't have any customizations, but I'll have a look in the file you mentioned and do some further testing. I ran the migration process several times because I had entered incorrect information (e.g. api token) the first 2 times. Maybe I should clean up the destination database and give it another try. Thanks for your help!

**Comment by DavidFeller** [comment]
The problem was obviously related to a "dirty" destination database. After setting up a new destination instance step 9 worked without any problems. 

You can close this issue if you like :)

**Comment by jensSeca** [comment]
Hey, I have the same issue. After found this issue, I create a new database with `bin/console pim:install --force --symlink --clean --env=prod`. But the error reappears... Any ideas?

**Comment by wbyrnetx** [comment]
I am also running into this issue trying to upgrade Akeneo from 1.x to 2.0.

It makes no sense to me why transporteo would try to add the "image_attribute_id" to the "pim_catalog_family" table on the destination Akeneo instance. That column has existing since version 2.0.0:
https://github.com/akeneo/pim-community-dev/blob/v2.0.0/src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Family.orm.yml

After commenting out the lines in src/Domain/MigrationStep/s080_FamilyMigration/FamilyDataMigrator.php that attempt to add the column, I continued getting DB schema related errors.

Am I missing something, or is this migration tool not compatible with a clean install of Akeneo 2.0?
